/* Generated by AN DISI Unibo */ 
package it.unibo.master4

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Master4 ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("MASTER 4 AVVIATO")
						utils.backupLastLog(  )
						utils.resetFile( "fileLog"  )
						utils.writeLog( "actorName | [backToCompensate - ] currentPosition | move | result\n"  )
						itunibo.coap.fridge.createClient( "localhost", 5684, "serverfridge"  )
					}
					 transition( edgeName="goto",targetState="scanningperimeter", cond=doswitch() )
				}	 
				state("scanningperimeter") { //this:State
					action { //it:State
						println("")
						println("State scanningperimeter")
						println("Inizio scansione della stanza.")
						forward("scanningPerimeter", "scanningPerimeter" ,"roomperimeterexplorer" ) 
					}
					 transition(edgeName="t00",targetState="findtable",cond=whenDispatch("endPerimeter"))
				}	 
				state("findtable") { //this:State
					action { //it:State
						println("")
						println("Fine scansione della stanza.")
						println("State findtable")
						println("Inizio ricerca del tavolo.")
						forward("scanningTable", "scanningTable" ,"findtable" ) 
					}
					 transition(edgeName="t11",targetState="executePrepare",cond=whenDispatch("homeReached"))
				}	 
				state("executePrepare") { //this:State
					action { //it:State
						println("")
						println("Fine ricerca del tavolo.")
						println("State executePrepare")
						delay(500) 
						println("Inizio prepare.")
						itunibo.coap.fridge.put( "expose"  )
						delay(1000) 
						forward("prepare", "prepare" ,"prepare" ) 
					}
					 transition(edgeName="t22",targetState="executeClear",cond=whenDispatch("endPrepare"))
				}	 
				state("executeClear") { //this:State
					action { //it:State
						println("")
						println("Fine prepare")
						println("State executeClear")
						delay(1000) 
						itunibo.coap.fridge.put( "C000"  )
						delay(500) 
						println("Inizio clear.")
						forward("clear", "clear" ,"clear" ) 
					}
					 transition(edgeName="t33",targetState="next",cond=whenDispatch("endClear"))
				}	 
				state("next") { //this:State
					action { //it:State
						println("")
						println("Fine clear")
						println("State next")
						delay(1000) 
						itunibo.coap.fridge.put( "C000"  )
						delay(500) 
						itunibo.coap.fridge.put( "C006"  )
						delay(500) 
						itunibo.coap.fridge.put( "C040"  )
						delay(500) 
						itunibo.coap.fridge.put( "expose"  )
						delay(1000) 
						println("Finito sprint4.")
					}
				}	 
			}
		}
}
