/* Generated by AN DISI Unibo */ 
package it.unibo.master1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Master1 ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "startscanningperimeter"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("startscanningperimeter") { //this:State
					action { //it:State
						println("Inizio scansione della stanza.")
						forward("scanningPerimeter", "scanningPerimeter" ,"roomperimeterexplorer" ) 
					}
					 transition(edgeName="t00",targetState="findtable",cond=whenDispatch("endPerimeter"))
				}	 
				state("findtable") { //this:State
					action { //it:State
						forward("scanningTable", "scanningTable" ,"findtable" ) 
					}
					 transition(edgeName="t11",targetState="endscanning",cond=whenDispatch("endScanningTable"))
				}	 
				state("endscanning") { //this:State
					action { //it:State
						println("Trovata la posizione del tavolo")
						delay(1000) 
						forward("goHome", "goHome" ,"workerinroom" ) 
					}
					 transition(edgeName="t22",targetState="returnHome",cond=whenDispatch("homeReached"))
				}	 
				state("returnHome") { //this:State
					action { //it:State
						forward("goalDirection", "goalDirection(downDir)" ,"workerinroom" ) 
					}
					 transition(edgeName="t33",targetState="executePrepare",cond=whenDispatch("directionReached"))
				}	 
				state("executePrepare") { //this:State
					action { //it:State
						println("Tornato a casa, ora ruoto")
						delay(500) 
						forward("startPrepare", "startPrepare" ,"prepare" ) 
					}
				}	 
			}
		}
}
